### ISSUE TITLE
Trying to use unstumble just takes me to your web page

### ISSUE THREAD

**Issue by gtackett** [zachflower/unstumble-chrome-extension#1]
Need I say more?

**Comment by zachflower** [comment]
Actually, yes, could you elaborate a little bit please?

Unstumble is a passive Google Chrome extension that redirects URLs that look like `www.stumbleupon.com/su/*` to their canonical source (for example, http://www.stumbleupon.com/su/2MBBxU gets automatically redirected to https://www.youtube.com/embed/dAfaM_CBvP8). 

Are you saying that all of your StumbleUpon links are getting redirected to my website?

Or are you trying to install it via the repository website link? If this is the case, that link was (admittedly) out of date, but it should now point to the proper landing page in the [Chrome Webstore](https://chrome.google.com/webstore/detail/unstumble/pmifhkljbaaaiobphihehgipahcmdgdh).

**Comment by gtackett** [comment]
Zach,
Sorry I didn't get back to you faster.
The problem wasn't with installing your extension.

After using stumbleupon to "stumble" to a page, I clicked on the Unstumble button in my Chrome toolbar. That's what keeps getting redirected to your website.
 
Galen

**Comment by zachflower** [comment]
Ah, okay, I understand now.

So, Unstumble is a passive plugin, not an active one, so the browser button isn't really intended to do anything (originally, the button wasn't there, but Chrome updated a while back and added a button for _all_ extensions).

The way Unstumble is supposed to work is when you land on a previously saved StumbleUpon link, Unstumble automatically strips the StumbleUpon URL and loads the _original_ link. For example, let's say you are using StumbleUpon on your phone, and save a link to this project for later in Pocket or Instapaper. The link that ends up in one of those services looks like http://www.stumbleupon.com/su/yaddayaddayadda, rather than https://github.com/zachflower/unstumble-chrome-extension. With Unstumble installed, when you navigate to that link you will be redirected to the GitHub link, rather than the StumbleUpon one.

The problem with the StumbleUpon links is that the original source content gets wrapped in an iframe with a big StumbleUpon toolbar at the top. The iframe prevents social media sites from properly parsing the in-page content (losing things like images, metadata, etc) and the toolbar is just intrusive to non-StumbleUpon users. The idea behind Unstumble is that it makes previously stumbled links significantly more shareable on social media.

I hope that helps clear things up, I'm sorry for the confusion!

**Comment by gtackett** [comment]
Zachary, I definitely understand better now how it works. Thanks!
